# fly.toml app configuration file generated for playwright-project on 2025-03-25T16:26:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'playwright-project'
primary_region = 'sea'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'


[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']



[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
  
